#!/usr/bin/env python3
"""
Majority voting simulation script for path-level analysis.

This script takes a CSV file generated by path_level_analysis.py and calculates
majority voting accuracy with and without pruning for different numbers of paths (k_paths).
"""

import pandas as pd
import argparse
import ast
import random
from collections import Counter
from typing import List, Any, Optional
import os


def _flatten(nested_list):
    """Flatten arbitrarily nested lists into a flat list (non-list elements)."""
    for item in nested_list:
        if isinstance(item, list):
            yield from _flatten(item)
        else:
            yield item


def parse_output_string(output_str: Any) -> Optional[List[Any]]:
    """Parse output string from CSV (e.g., "[0, 1, 2]" or "syntax error" or None)."""
    # Handle pandas None values
    if pd.isna(output_str) or output_str is None:
        return None
    
    # Convert to string for comparison (handles numeric types)
    if not isinstance(output_str, str):
        output_str = str(output_str)
    
    if output_str == 'syntax error':
        return 'syntax error'
    
    try:
        # Try to parse as Python literal
        parsed = ast.literal_eval(output_str)
        # Normalize to list format
        if isinstance(parsed, list):
            return parsed
        elif isinstance(parsed, int):
            return [parsed]
        else:
            return None
    except (ValueError, SyntaxError):
        # Return None for invalid strings instead of raising
        return None

def extract_answer_from_output(parsed_output: Any, dataset: str) -> Optional[Any]:
    """Extract answer from parsed output for comparison.
    
    Returns a hashable tuple representation of the answer(s).
    """
    if parsed_output is None or parsed_output == 'syntax error':
        return None
    
    try:
        flat_output = list(_flatten(parsed_output))
        if len(flat_output) == 0:
            return None
        
        # Check if all elements are hashable
        for item in flat_output:
            if isinstance(item, (list, dict, set)):
                # Skip outputs with unhashable elements
                return None
        
        # Convert to tuple for hashability (can be used in Counter)
        return tuple(flat_output)
    except (TypeError, ValueError):
        # If flattening fails or other issues, skip this output
        return None


def is_voting_result_correct(voting_result: Any, true_label: str, dataset: str) -> bool:
    """Check if voting result matches true label.
    
    For single-answer results: exact match
    For multi-answer results: true_label must be in the result
    """
    if voting_result is None:
        return False
    
    try:
        # Convert tuple back to list if needed
        if isinstance(voting_result, tuple):
            voting_result = list(voting_result)
        
        # If voting_result is a list with multiple items, check if true_label is in it
        if isinstance(voting_result, list):
            if len(voting_result) != 1:
                return False
            else:
                # Single answer - exact match
                voting_answer = voting_result[0]
        else:
            raise ValueError(f"Unexpected voting result type: {type(voting_result)}")
            
        
        # Handle single answer formats
        if dataset and dataset.lower() == 'ar-lsat':
            # AR-LSAT: numeric comparison
            voting_answer = int(voting_answer)
            true_label_int = int(true_label)
            return voting_answer == true_label_int
        elif dataset and dataset.lower() in ['proofwriter', 'folio']:
            # ProofWriter/FOLIO: mapping between boolean and letters
            return (voting_answer == "True" and true_label == "A") or \
                   (voting_answer == "False" and true_label == "B") or \
                   (voting_answer == "Unknown" and true_label == "C")
        elif dataset and dataset.lower() == 'prontoqa':
            # ProntoQA: mapping between boolean and letters
            return (voting_answer == "True" and true_label == "A") or \
                   (voting_answer == "False" and true_label == "B")
        elif dataset and dataset.lower() == 'logicaldeduction':
            # LogicalDeduction: direct letter comparison
            return str(voting_answer) == str(true_label)
        else:
            raise ValueError(f"Unsupported dataset: {dataset}")
            
    except (ValueError, TypeError):
        return False


def majority_vote(outputs: List[Any], dataset: str) -> Optional[Any]:
    """Perform majority voting on a list of outputs.
    
    Returns the most frequent output (as a tuple for hashability).
    """
    # Extract answers from each output
    answers = []
    for output in outputs:
        if output is None or output == 'syntax error':
            continue  # Skip None and syntax errors
        answer = extract_answer_from_output(output, dataset)
        if answer is not None:
            answers.append(answer)
    
    if len(answers) == 0:
        return None
    
    # Count occurrences (answers are tuples, so they're hashable)
    counter = Counter(answers)
    
    # Get the most common answer (returns tuple)
    most_common = counter.most_common(1)[0]
    
    return most_common[0]


def simulate_majority_voting(
    df: pd.DataFrame,
    k_paths: int,
    simulation: int,
    use_pruning: bool,
    dataset: str
) -> dict:
    """Simulate majority voting for a given k_paths and simulation number."""
    # Group by sample_id
    grouped = df.groupby('sample_id')
    
    total_samples = 0
    correct_samples = 0
    
    for sample_id, group in grouped:
        # Get all paths for this sample
        paths = group.sort_values('path_index').copy()
        
        # Get true_label (should be same for all paths of same sample)
        true_label = paths.iloc[0]['true_label']
        
        # Randomly sample k_paths paths
        available_paths = len(paths)
        if available_paths == 0:
            continue
        
        total_samples += 1
        
        # Sample k_paths paths (or all if fewer available)
        k = min(k_paths, available_paths)
        
        # Use a deterministic seed for reproducibility
        # Combine simulation, k_paths, and sample_id for unique but reproducible seeds
        # Convert sample_id to a number for deterministic hashing
        sample_id_hash = abs(hash(str(sample_id))) % (10**9)
        sample_seed = (simulation * 1000000 + k_paths * 1000 + sample_id_hash) % (2**31)
        sampled_paths = paths.sample(n=k, random_state=sample_seed)
        
        # Collect outputs
        if use_pruning:
            # Use existence_uniqueness_pruning_result
            outputs = [
                parse_output_string(str(row['existence_uniqueness_pruning_result']))
                for _, row in sampled_paths.iterrows()
            ]
        else:
            # Use parsed_output
            outputs = [
                parse_output_string(str(row['parsed_output']))
                for _, row in sampled_paths.iterrows()
            ]
        
        # Filter out None values (pruned paths)
        outputs = [out for out in outputs if out is not None]
        
        # Perform majority voting
        voting_result = majority_vote(outputs, dataset)
        
        # Check correctness
        is_correct = is_voting_result_correct(voting_result, true_label, dataset)
        
        if is_correct:
            correct_samples += 1
    
    accuracy = correct_samples / total_samples if total_samples > 0 else 0.0
    
    return {
        'k_paths': k_paths,
        'simulation': simulation,
        'accuracy': accuracy,
        'total_samples': total_samples,
        'correct_samples': correct_samples,
        'cot_backup_used': 0  # Not used in this simulation
    }


def main():
    parser = argparse.ArgumentParser(
        description='Simulate majority voting with and without pruning for path-level analysis.',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument('input_csv', 
                       help='Path to CSV file generated by path_level_analysis.py')
    parser.add_argument('--output-csv', type=str,
                       help='Output CSV file path (default: input_csv with _simulation suffix)')
    parser.add_argument('--max-paths', type=int, default=20,
                       help='Maximum number of paths to simulate (default: 20)')
    parser.add_argument('--num-simulations', type=int, default=10,
                       help='Number of simulations per k_paths (default: 10)')
    parser.add_argument('--with-pruning', action='store_true',
                       help='Calculate accuracy with pruning (default: without pruning)')
    parser.add_argument('--both', action='store_true',
                       help='Calculate both with and without pruning (saves two files)')
    
    args = parser.parse_args()
    
    # Load CSV
    print(f"Loading CSV from: {args.input_csv}")
    df = pd.read_csv(args.input_csv)
    
    # Get dataset from first row (should be same for all)
    dataset = df.iloc[0]['dataset']
    print(f"Dataset: {dataset}")
    
    # Determine max available paths
    max_available_paths = df.groupby('sample_id').size().max()
    max_paths = min(args.max_paths, max_available_paths)
    print(f"Max available paths per sample: {max_available_paths}")
    print(f"Simulating up to {max_paths} paths")
    
    # Determine what to calculate
    if args.both:
        pruning_modes = [False, True]
        mode_names = ['no_pruning', 'existence_uniqueness_pruning']
    elif args.with_pruning:
        pruning_modes = [True]
        mode_names = ['existence_uniqueness_pruning']
    else:
        pruning_modes = [False]
        mode_names = ['no_pruning']
    
    # Run simulations
    for use_pruning, mode_name in zip(pruning_modes, mode_names):
        print(f"\n{'='*60}")
        print(f"Simulating majority voting: {mode_name}")
        print(f"{'='*60}")
        
        results = []
        
        for k in range(1, max_paths + 1):
            for sim in range(args.num_simulations):
                print(f"k_paths={k}, simulation={sim}...", end='\r')
                result = simulate_majority_voting(
                    df, k, sim, use_pruning, dataset
                )
                results.append(result)
        
        print()  # New line after progress
        
        # Create results DataFrame
        results_df = pd.DataFrame(results)
        
        # Calculate summary statistics
        summary = results_df.groupby('k_paths')['accuracy'].agg(['mean', 'std', 'min', 'max']).reset_index()
        # Format the mean±std column
        summary['mean±std'] = summary.apply(
            lambda row: f"{row['mean']:.4f}±{row['std']:.4f}", axis=1
        )
        # Reorder columns
        summary = summary[['k_paths', 'mean', 'std', 'mean±std', 'min', 'max']]
        
        # Determine output file
        if args.output_csv:
            if args.both:
                # Add suffix for pruning mode
                base_name = args.output_csv.rsplit('.', 1)[0]
                output_file = f"{base_name}_{mode_name}.xlsx"
            else:
                base_name = args.output_csv.rsplit('.', 1)[0]
                output_file = f"{base_name}.xlsx"
        else:
            # Generate output filename from input
            base_name = args.input_csv.rsplit('.', 1)[0]
            output_file = f"{base_name}_simulation_{mode_name}.xlsx"
        
        # Save results to Excel with multiple sheets
        with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
            results_df.to_excel(writer, sheet_name='Raw Results', index=False)
            summary.to_excel(writer, sheet_name='Statistics', index=False)
        
        print(f"\nResults saved to: {output_file}")
        print(f"  - Sheet 'Raw Results': {len(results_df)} rows")
        print(f"  - Sheet 'Statistics': {len(summary)} rows")
        
        # Print summary statistics
        print(f"\nSummary by k_paths:")
        print(summary.to_string(index=False))
        
        # Also save CSV version for backward compatibility
        csv_output_file = output_file.replace('.xlsx', '.csv')
        results_df.to_csv(csv_output_file, index=False)
        print(f"\nCSV version also saved to: {csv_output_file}")
    
    print("\nDone!")


if __name__ == "__main__":
    main()

