#!/usr/bin/env python3
"""
Majority Vote Ablation Analysis Script

This script performs ablation analysis on accuracy vs number of paths using majority vote.
It takes path-level CSV files generated by path_level_analysis.py and performs majority voting
on k selected paths (1, 3, 5, 7, ..., max_paths) for each sample.

Usage:
    python majority_vote_ablation.py <csv_file> [--max-paths 30] [--output results.csv]
"""

import pandas as pd
import numpy as np
import ast
import argparse
import os
import sys
from collections import Counter
from pathlib import Path
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import random


def safe_literal_eval(s):
    """Safely evaluate string representation of Python literals."""
    if pd.isna(s) or s == '' or s == 'syntax error':
        return []
    
    try:
        if isinstance(s, str):
            s = s.strip()
            if s == '[]':
                return []
            elif s.startswith('[') and s.endswith(']'):
                return ast.literal_eval(s)
            else:
                return []
        return []
    except (ValueError, SyntaxError):
        return []


def majority_vote(parsed_outputs):
    """
    Perform majority vote on a list of parsed outputs, filtering out syntax errors.
    
    Args:
        parsed_outputs: List of parsed outputs (strings like '[A, B]', 'syntax error', etc.)
    
    Returns:
        String representing the majority vote result
    
    Examples with K=3:
        ['[A, B]', '[B, C]', 'syntax error'] -> '[A, B]' or '[B, C]' (tie)
        ['[A, B]', '[A, B]', '[A, B, C]'] -> '[A, B]'
        ['[A]', '[A]', '[A, B, C]'] -> '[A]'
        ['[]', '[]', '[A]'] -> '[]'
    """
    if not parsed_outputs: # if parsed_outputs is empty, return []
        return '[]'
    
    # Filter out syntax errors
    valid_outputs = [output for output in parsed_outputs if output != 'syntax error']
    
    # If no valid outputs, return []
    if not valid_outputs:
        return '[]'
    
    # Count occurrences of each valid parsed output
    output_counts = Counter(valid_outputs)
    
    # Find the most common output
    most_common = output_counts.most_common(1)[0][0]
    
    return most_common


def cot_backup_filter(majority_result, sampled_paths, pruning_column, true_label, use_cot_backup):
    """
    Apply CoT backup logic based on majority vote result and pruning column.
    
    Args:
        majority_result: The result from majority voting
        sampled_paths: DataFrame containing the sampled paths for this sample
        pruning_column: The column used for pruning/voting
        true_label: The correct answer for this sample
        use_cot_backup: Whether CoT backup is enabled
    
    Returns:
        tuple: (final_result, used_cot_backup, backup_reason)
    """
    used_cot_backup = False
    backup_reason = None
    final_result = majority_result
    
    if not use_cot_backup or 'cot_correctness' not in sampled_paths.columns:
        return final_result, used_cot_backup, backup_reason
    
    # Get CoT correctness for this sample (should be same for all paths)
    cot_correct = sampled_paths.iloc[0]['cot_correctness']
    should_use_backup = False
    
    if pd.notna(cot_correct) and cot_correct:        
        # Case 1: Existence pruning - if result is empty, use CoT as backup
        if pruning_column == 'existence_pruning_result' and majority_result == '[]':
            should_use_backup = True
            backup_reason = 'existence_empty'
        
        # Case 2: Uniqueness pruning - if result has more than 1 element, use CoT as backup
        if pruning_column == 'uniqueness_pruning_result':
            try:
                parsed_result = safe_literal_eval(majority_result)
                if isinstance(parsed_result, list) and len(parsed_result) > 1:
                    should_use_backup = True
                    backup_reason = 'uniqueness_multiple'
            except:
                pass
        
        # Case 3: Combined pruning (existence + uniqueness) - empty result
        if pruning_column == 'existence_uniqueness_pruning_result' and majority_result == '[]':
            should_use_backup = True
            backup_reason = 'combined_empty'
        
        # Use CoT result as backup if any condition is met
        if should_use_backup:
            final_result = f'[{true_label}]'
            used_cot_backup = True
    
    return final_result, used_cot_backup, backup_reason


def calculate_accuracy_for_k_paths(df, k, dataset, random_sample=False, seed=None, use_pruned=False, pruning_column='parsed_output', use_cot_backup=False):
    """Calculate accuracy using majority vote on k paths for each sample."""
    if seed is not None:
        random.seed(seed)
    
    results = []
    
    # Group by sample_id
    for sample_id, group in df.groupby('sample_id'):
        group_sorted = group.sort_values('path_index')
        
        if random_sample:
            # Always randomly sample k paths (or all available if fewer than k)
            n_sample = min(k, len(group_sorted))
            sampled_paths = group_sorted.sample(n=n_sample, random_state=seed)
        else:
            # Take first k paths
            sampled_paths = group_sorted.head(k)
        
        if len(sampled_paths) == 0:
            continue
            
        # Get true label (should be same for all paths of this sample)
        true_label = sampled_paths.iloc[0]['true_label']
        
        # Extract parsed outputs as strings (no preprocessing)
        parsed_outputs = []
        for _, row in sampled_paths.iterrows():
            # Use the specified pruning column (default: 'parsed_output')
            if pruning_column in row and pd.notna(row[pruning_column]):
                parsed_output = str(row[pruning_column])
            else:
                parsed_output = 'syntax error'
            parsed_outputs.append(parsed_output)
        
        # Perform majority vote
        majority_result = majority_vote(parsed_outputs)
        
        # Apply CoT backup filter
        majority_result, used_cot_backup, backup_reason = cot_backup_filter(
            majority_result, sampled_paths, pruning_column, true_label, use_cot_backup)
        
        # Determine correctness based on dataset
        is_correct = is_majority_vote_correct(majority_result, true_label, dataset)
        
        results.append({
            'sample_id': sample_id,
            'k_paths': k,
            'majority_vote_result': majority_result,
            'true_label': true_label,
            'is_correct': is_correct,
            'total_paths_used': len(parsed_outputs),
            'simulation_seed': seed if random_sample else None,
            'used_cot_backup': used_cot_backup,
            'backup_reason': backup_reason
        })
    
    return results


def is_majority_vote_correct(majority_result, true_label, dataset):
    """Determine if majority vote result is correct based on dataset format."""
    if majority_result == 'syntax error':  # Syntax error is always incorrect
        return False
    
    try:
        # Parse the majority result to extract the answer
        parsed_result = safe_literal_eval(majority_result)
        
        if not parsed_result or len(parsed_result) != 1:  # Should have exactly one answer
            return False
        
        predicted_answer = parsed_result[0]
        
        # Handle different dataset formats
        if dataset.upper() == 'AR-LSAT':
            # AR-LSAT: numeric comparison
            return int(predicted_answer) == int(true_label)
        elif dataset.upper() in ['PROOFWRITER', 'FOLIO']:
            # ProofWriter/FOLIO: mapping between boolean and letters
            return (predicted_answer == "True" and true_label == "A") or \
                   (predicted_answer == "False" and true_label == "B") or \
                   (predicted_answer == "Unknown" and true_label == "C")
        elif dataset.upper() == 'PRONTOQA':
            # ProntoQA: mapping between boolean and letters
            return (predicted_answer == "True" and true_label == "A") or \
                   (predicted_answer == "False" and true_label == "B")
        elif dataset.upper() == 'LOGICALDEDUCTION':
            # LogicalDeduction: direct letter comparison
            return str(predicted_answer) == str(true_label)
        else:
            # Default: string comparison
            return str(predicted_answer) == str(true_label)
    except (ValueError, TypeError):
        return False


def run_simulation_analysis(df, max_paths=30, num_simulations=50, pruning_column='parsed_output', use_cot_backup=False):
    """Run multiple simulation analysis with random sampling and error bars."""
    if df.empty:
        return pd.DataFrame(), pd.DataFrame()
    
    # Get dataset name
    dataset = df['dataset'].iloc[0] if 'dataset' in df.columns else 'unknown'
    
    # Determine actual max paths available
    max_available_paths = df.groupby('sample_id')['path_index'].max().max() + 1
    actual_max_paths = min(max_paths, max_available_paths)
    
    print(f"Dataset: {dataset}")
    print(f"Max paths requested: {max_paths}")
    print(f"Max paths available: {max_available_paths}")
    print(f"Using max paths: {actual_max_paths}")
    print(f"Number of simulations: {num_simulations}")
    if use_cot_backup:
        print(f"CoT backup enabled for existence_uniqueness_pruning_result")
    
    # Generate k values: 1, 2, 3, 4, ..., max_paths
    k_values = list(range(1, actual_max_paths + 1))
    
    print(f"Testing k values: {k_values}")
    
    all_results = []
    simulation_results = []
    
    for k in k_values:
        print(f"Processing k={k} paths...")
        k_accuracies = []
        k_cot_backup_usage = []
        
        for sim in range(num_simulations):
            # Always use random sampling for all k values
            seed = sim
            
            k_results = calculate_accuracy_for_k_paths(df, k, dataset, 
                                                     random_sample=True, 
                                                     seed=seed,
                                                     pruning_column=pruning_column,
                                                     use_cot_backup=use_cot_backup)
            all_results.extend(k_results)
            
            # Calculate accuracy and CoT backup usage for this simulation
            if k_results:
                accuracy = sum(r['is_correct'] for r in k_results) / len(k_results)
                cot_backup_used = sum(r.get('used_cot_backup', False) for r in k_results)
                
                # Count backup usage by reason
                backup_reasons = {}
                for r in k_results:
                    if r.get('used_cot_backup', False) and r.get('backup_reason'):
                        reason = r['backup_reason']
                        backup_reasons[reason] = backup_reasons.get(reason, 0) + 1
                
                k_accuracies.append(accuracy)
                k_cot_backup_usage.append(cot_backup_used)
                
                sim_result = {
                    'k_paths': k,
                    'simulation': sim,
                    'accuracy': accuracy,
                    'total_samples': len(k_results),
                    'correct_samples': sum(r['is_correct'] for r in k_results),
                    'cot_backup_used': cot_backup_used
                }
                
                # Add backup reason counts
                for reason, count in backup_reasons.items():
                    sim_result[f'backup_{reason}'] = count
                
                simulation_results.append(sim_result)
        
        if use_cot_backup and k_cot_backup_usage:
            avg_cot_usage = np.mean(k_cot_backup_usage)
            print(f"  k={k}: mean={np.mean(k_accuracies):.4f}, std={np.std(k_accuracies):.4f}, avg_cot_backup={avg_cot_usage:.1f}")
        else:
            print(f"  k={k}: mean={np.mean(k_accuracies):.4f}, std={np.std(k_accuracies):.4f}")
    
    # Convert to DataFrames
    results_df = pd.DataFrame(all_results)
    simulation_df = pd.DataFrame(simulation_results)
    
    return results_df, simulation_df


def run_ablation_analysis(df, max_paths=30, pruning_column='parsed_output'):
    """Run complete ablation analysis for different values of k (original deterministic version)."""
    if df.empty:
        return pd.DataFrame()
    
    # Get dataset name
    dataset = df['dataset'].iloc[0] if 'dataset' in df.columns else 'unknown'
    
    # Determine actual max paths available
    max_available_paths = df.groupby('sample_id')['path_index'].max().max() + 1
    actual_max_paths = min(max_paths, max_available_paths)
    
    print(f"Dataset: {dataset}")
    print(f"Max paths requested: {max_paths}")
    print(f"Max paths available: {max_available_paths}")
    print(f"Using max paths: {actual_max_paths}")
    
    # Generate k values: 1, 2, 3, 4, ..., max_paths
    k_values = list(range(1, actual_max_paths + 1))
    
    print(f"Testing k values: {k_values}")
    
    all_results = []
    
    for k in k_values:
        print(f"Processing k={k} paths...")
        k_results = calculate_accuracy_for_k_paths(df, k, dataset, pruning_column=pruning_column)
        all_results.extend(k_results)
    
    # Convert to DataFrame
    results_df = pd.DataFrame(all_results)
    
    # Calculate summary statistics
    summary_stats = []
    for k in k_values:
        k_data = results_df[results_df['k_paths'] == k]
        if len(k_data) > 0:
            accuracy = k_data['is_correct'].mean()
            total_samples = len(k_data)
            correct_samples = k_data['is_correct'].sum()
            
            summary_stats.append({
                'k_paths': k,
                'total_samples': total_samples,
                'correct_samples': correct_samples,
                'accuracy': accuracy
            })
    
    summary_df = pd.DataFrame(summary_stats)
    
    return results_df, summary_df


def plot_error_shade(simulation_df, output_file=None, csv_file=None, title_suffix=""):
    """Create error shade plot from simulation results using standard deviation."""
    # Calculate statistics for each k
    stats = simulation_df.groupby('k_paths')['accuracy'].agg([
        'mean', 'std', 'count'
    ]).reset_index()
    
    # Use standard deviation for shading
    stats['upper'] = stats['mean'] + stats['std']
    stats['lower'] = stats['mean'] - stats['std']
    
    # Set up the plot style
    try:
        plt.style.use('seaborn-v0_8')
    except:
        try:
            plt.style.use('seaborn')
        except:
            pass  # Use default style
    
    fig, ax = plt.subplots(figsize=(6, 6))
    
    # Create the main line plot
    ax.plot(stats['k_paths'], stats['mean'], 
            marker='o', linewidth=2.5, markersize=6,
            color='steelblue', alpha=0.9, label='Mean Accuracy')
    
    # Add shaded error region (±1 standard deviation)
    ax.fill_between(stats['k_paths'], stats['lower'], stats['upper'], 
                    alpha=0.3, color='steelblue', 
                    label='±1 Standard Deviation')
    
    # Customize the plot
    ax.set_xlabel('Number of Paths (K)', fontsize=12, fontweight='bold')
    ax.set_ylabel('Accuracy', fontsize=12, fontweight='bold')
    # ax.set_title('Majority Vote Accuracy vs Number of Paths\n(with Standard Deviation)', 
                #  fontsize=14, fontweight='bold', pad=20)
    
    # set xlim to 1 to max_paths
    ax.set_xlim(1, stats['k_paths'].max())
    # set x ticks to 1 to max_paths
    ax.set_xticks(np.arange(1, stats['k_paths'].max() + 1))
    # Format axes
    ax.grid(True, alpha=0.3)
    ax.set_ylim(max(0, min(stats['lower']) * 0.95), 
                max(stats['upper']) * 1.05)
    
    # Add legend
    ax.legend(loc='best', framealpha=0.9)
    
    # Note: Removed value labels on points as requested
    
    plt.tight_layout()
    
    # Save plot
    if output_file:
        # Use PDF format and add input file name split by / and take the last part before .csv
        base_name = os.path.basename(csv_file).split('/')[-1].split('.csv')[0]
        pdf_output = f"{base_name}_path_ablation.pdf"
        plt.savefig(pdf_output, format='pdf', dpi=300, bbox_inches='tight')
        print(f"Plot saved to: {pdf_output}")
    
    plt.show()
    
    return fig, ax


def plot_comparison_error_shade(simulation_df1, simulation_df2, output_file=None, csv_file=None, 
                               label1="Multi-path Ensemble", label2="Pruning Before Multi-path Ensemble"):
    """Create comparison plot with two lines from two simulation results."""
    # Calculate statistics for each simulation dataset
    stats1 = simulation_df1.groupby('k_paths')['accuracy'].agg(['mean', 'std', 'count']).reset_index()
    stats2 = simulation_df2.groupby('k_paths')['accuracy'].agg(['mean', 'std', 'count']).reset_index()
    
    # Use standard deviation for shading
    stats1['upper'] = stats1['mean'] + stats1['std']
    stats1['lower'] = stats1['mean'] - stats1['std']
    stats2['upper'] = stats2['mean'] + stats2['std']
    stats2['lower'] = stats2['mean'] - stats2['std']
    
    # Set up the plot style
    try:
        plt.style.use('seaborn-v0_8')
    except:
        try:
            plt.style.use('seaborn')
        except:
            pass  # Use default style
    
    fig, ax = plt.subplots(figsize=(6, 6))
    
    # Create the first line plot
    ax.plot(stats1['k_paths'], stats1['mean'], 
            marker='o', linewidth=2.5, markersize=6,
            color='steelblue', alpha=0.9, label=label1)
    
    # Add shaded error region for first line
    ax.fill_between(stats1['k_paths'], stats1['lower'], stats1['upper'], 
                    alpha=0.2, color='steelblue')
    
    # Create the second line plot
    ax.plot(stats2['k_paths'], stats2['mean'], 
            marker='s', linewidth=2.5, markersize=6,
            color='darkorange', alpha=0.9, label=label2)
    
    # Add shaded error region for second line
    ax.fill_between(stats2['k_paths'], stats2['lower'], stats2['upper'], 
                    alpha=0.2, color='darkorange')
    
    # Customize the plot
    ax.set_xlabel('Number of Paths (K)', fontsize=12, fontweight='bold')
    ax.set_ylabel('Accuracy', fontsize=12, fontweight='bold')
    # ax.set_title('Majority Vote Accuracy Comparison\n(with Standard Deviation)', 
                #  fontsize=14, fontweight='bold', pad=20)
    
    # Set xlim and xticks
    max_k = max(stats1['k_paths'].max(), stats2['k_paths'].max())
    ax.set_xlim(1, max_k)
    ax.set_xticks(np.arange(1, max_k + 1))
    
    # Format axes
    ax.grid(True, alpha=0.3)
    
    # Calculate y-axis limits based on both datasets
    all_lower = min(stats1['lower'].min(), stats2['lower'].min())
    all_upper = max(stats1['upper'].max(), stats2['upper'].max())
    ax.set_ylim(max(0, all_lower * 0.95), all_upper * 1.05)
    
    # Add legend
    ax.legend(loc='best', framealpha=0.9)
    
    plt.tight_layout()
    
    # Save plot
    if output_file:
        # Use PDF format and add input file name
        base_name = os.path.basename(csv_file).split('/')[-1].split('.csv')[0]
        pdf_output = f"{base_name}_comparison_path_ablation.pdf"
        plt.savefig(pdf_output, format='pdf', dpi=300, bbox_inches='tight')
        print(f"Comparison plot saved to: {pdf_output}")
    
    plt.show()
    
    return fig, ax


def generate_pruning_comparison_table(df, csv_file, k=20, num_simulations=10, use_cot_backup=False):
    """Generate comparison table for different pruning methods at k=5."""
    print(f"\n{'='*60}")
    print(f"PRUNING COMPARISON TABLE (k={k}, {num_simulations} simulations)")
    print(f"{'='*60}")
    
    dataset = df['dataset'].iloc[0] if 'dataset' in df.columns else 'unknown'
    
    # Define the pruning methods and their corresponding columns
    methods = [
        ('None (use parsed_output only)', 'parsed_output'),
        ('P1 (existence)', 'existence_pruning_result'),
        ('P2 (uniqueness)', 'uniqueness_pruning_result'),
        ('P1+P2', 'existence_uniqueness_pruning_result')
    ]
    
    results_table = []
    
    for method_name, column_name in methods:
        print(f"\nProcessing {method_name}...")
        
        # Check if column exists
        if column_name not in df.columns:
            print(f"Warning: Column {column_name} not found, skipping...")
            continue
        
        # Run simulations for this method
        accuracies = []
        for sim in range(num_simulations):
            seed = sim
            k_results = calculate_accuracy_for_k_paths(df, k, dataset, 
                                                     random_sample=True, 
                                                     seed=seed,
                                                     pruning_column=column_name,
                                                     use_cot_backup=use_cot_backup)
            
            if k_results:
                accuracy = sum(r['is_correct'] for r in k_results) / len(k_results)
                accuracies.append(accuracy)
        
        if accuracies:
            mean_acc = np.mean(accuracies)
            std_acc = np.std(accuracies)
            results_table.append({
                'Method': method_name,
                'Column': column_name,
                'Mean_Accuracy': mean_acc,
                'Std_Accuracy': std_acc,
                'Accuracies': accuracies
            })
            print(f"  Mean: {mean_acc:.4f}, Std: {std_acc:.4f}")
    
    # Create and display table
    if results_table:
        print(f"\n{'='*60}")
        print("SUMMARY TABLE")
        print(f"{'='*60}")
        print(f"{'Method':<35} {'Accuracy':<15} {'Std':<10}")
        print("-" * 60)
        
        for result in results_table:
            method_short = result['Method'].split(' (')[0]  # Shorten method name
            print(f"{method_short:<35} {result['Mean_Accuracy']:<15.4f} {result['Std_Accuracy']:<10.4f}")
        
        # Save detailed results to CSV
        base_name = os.path.splitext(os.path.basename(csv_file))[0]
        output_file = f"{base_name}_pruning_comparison_k{k}.csv"
        
        # Create detailed CSV with all simulation results
        detailed_data = []
        for result in results_table:
            for sim_idx, acc in enumerate(result['Accuracies']):
                detailed_data.append({
                    'Method': result['Method'],
                    'Column': result['Column'],
                    'Simulation': sim_idx,
                    'Accuracy': acc
                })
        
        detailed_df = pd.DataFrame(detailed_data)
        detailed_df.to_csv(output_file, index=False)
        print(f"\nDetailed results saved to: {output_file}")
        
        # Create summary CSV
        summary_file = f"{base_name}_pruning_summary_k{k}.csv"
        summary_data = []
        for result in results_table:
            summary_data.append({
                'Method': result['Method'],
                'Column': result['Column'],
                'Mean_Accuracy': result['Mean_Accuracy'],
                'Std_Accuracy': result['Std_Accuracy'],
                'K_Paths': k,
                'Num_Simulations': num_simulations
            })
        
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_csv(summary_file, index=False)
        print(f"Summary table saved to: {summary_file}")
        
        return summary_df
    
    return None


def process_single_file(csv_file, max_paths=30, num_simulations=50, use_simulations=False, enable_cot_backup=False):
    """Process a single CSV file and return results for both pruning methods."""
    print(f"\nProcessing file: {csv_file}")
    
    # Load data
    try:
        df = pd.read_csv(csv_file)
    except Exception as e:
        print(f"Error loading {csv_file}: {e}")
        return None, None, None, None, None, None, None
    
    print(f"Loaded {len(df)} rows")
    
    # Basic info
    if 'sample_id' not in df.columns:
        print("Error: 'sample_id' column not found")
        return None, None, None, None, None, None, None
    
    num_samples = df['sample_id'].nunique()
    num_paths_per_sample = df.groupby('sample_id').size()
    
    print(f"Number of samples: {num_samples}")
    print(f"Paths per sample - min: {num_paths_per_sample.min()}, max: {num_paths_per_sample.max()}, mean: {num_paths_per_sample.mean():.1f}")
    
    # Check if existence_uniqueness_pruning_result column exists
    has_pruning_column = 'existence_uniqueness_pruning_result' in df.columns
    has_cot_column = 'cot_correctness' in df.columns
    print(f"Has existence_uniqueness_pruning_result column: {has_pruning_column}")
    print(f"Has cot_correctness column: {has_cot_column}")
    
    # CoT backup is only enabled for existence_uniqueness_pruning_result when both columns exist
    use_cot_backup_for_pruning = enable_cot_backup and has_pruning_column and has_cot_column
    if enable_cot_backup and not has_cot_column:
        print("Warning: CoT backup requested but cot_correctness column not found")
    
    # Run analysis for parsed_output
    print("\n=== Processing with parsed_output ===")
    if use_simulations:
        results_df1, simulation_df1 = run_simulation_analysis(df, max_paths, num_simulations, 'parsed_output', use_cot_backup=False)
        
        # Calculate summary statistics from simulations
        summary_stats1 = simulation_df1.groupby('k_paths')['accuracy'].agg([
            'mean', 'std', 'count'
        ]).reset_index()
        summary_stats1.rename(columns={'mean': 'accuracy'}, inplace=True)
        summary_stats1['total_samples'] = num_samples
        summary_stats1['correct_samples'] = (summary_stats1['accuracy'] * num_samples).round().astype(int)
        
        summary_df1 = summary_stats1[['k_paths', 'total_samples', 'correct_samples', 'accuracy', 'std']]
    else:
        results_df1, summary_df1 = run_ablation_analysis(df, max_paths, 'parsed_output')
        simulation_df1 = None
    
    # Run analysis for existence_uniqueness_pruning_result if available
    results_df2, summary_df2, simulation_df2 = None, None, None
    if has_pruning_column:
        print("\n=== Processing with existence_uniqueness_pruning_result ===")
        if use_cot_backup_for_pruning:
            print("CoT backup will be used when majority vote result is empty")
        
        if use_simulations:
            results_df2, simulation_df2 = run_simulation_analysis(df, max_paths, num_simulations, 
                                                                 'existence_uniqueness_pruning_result', 
                                                                 use_cot_backup=use_cot_backup_for_pruning)
            
            # Calculate summary statistics from simulations
            summary_stats2 = simulation_df2.groupby('k_paths')['accuracy'].agg([
                'mean', 'std', 'count'
            ]).reset_index()
            summary_stats2.rename(columns={'mean': 'accuracy'}, inplace=True)
            summary_stats2['total_samples'] = num_samples
            summary_stats2['correct_samples'] = (summary_stats2['accuracy'] * num_samples).round().astype(int)
            
            summary_df2 = summary_stats2[['k_paths', 'total_samples', 'correct_samples', 'accuracy', 'std']]
        else:
            results_df2, summary_df2 = run_ablation_analysis(df, max_paths, 'existence_uniqueness_pruning_result')
            simulation_df2 = None
    
    # Extract experiment info
    exp_info = {
        'experiment_id': df['experiment_id'].iloc[0] if 'experiment_id' in df.columns else 'unknown',
        'dataset': df['dataset'].iloc[0] if 'dataset' in df.columns else 'unknown',
        'total_samples': num_samples,
        'max_paths_per_sample': num_paths_per_sample.max()
    }
    
    return results_df1, summary_df1, simulation_df1, results_df2, summary_df2, simulation_df2, exp_info


def main():
    parser = argparse.ArgumentParser(
        description='Majority vote ablation analysis on path-level results.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python majority_vote_ablation.py path-level-analysis/experiment_path_level.csv
    python majority_vote_ablation.py path-level-analysis/experiment_path_level.csv --max-paths 30
    python majority_vote_ablation.py path-level-analysis/experiment_path_level.csv --simulations --num-simulations 10 --plot (optional: --cot-backup )
    python majority_vote_ablation.py path-level-analysis/experiment_path_level.csv --ablation_study_3dot2_table (optional: --cot-backup)
    """
    )
    
    parser.add_argument('csv_file',
                       help='Path-level CSV file to analyze')
    
    parser.add_argument('--max-paths', type=int, default=30,
                       help='Maximum number of paths to consider (default: 30)')
    
    parser.add_argument('--output', type=str,
                       help='Output CSV file for detailed results')
    
    parser.add_argument('--simulations', action='store_true',
                       help='Run multiple simulations with random path sampling')
    
    parser.add_argument('--num-simulations', type=int, default=50,
                       help='Number of simulations to run (default: 50)')
    
    parser.add_argument('--plot', action='store_true',
                       help='Generate error bar plot')
    
    parser.add_argument('--ablation_study_3dot2_table', action='store_true',
                       help='Generate comparison table for different pruning methods (default: k=20, 10 simulations)')
    
    parser.add_argument('--cot-backup', action='store_true',
                       help='Enable CoT backup for failed majority votes (syntax errors, empty results, multiple elements)')
    
    args = parser.parse_args()
    
    csv_file = args.csv_file
    if not os.path.exists(csv_file):
        print(f"Error: File not found: {csv_file}")
        sys.exit(1)
    
    # Handle table generation mode
    if args.ablation_study_3dot2_table:
        # Load data for table generation
        try:
            df = pd.read_csv(csv_file)
        except Exception as e:
            print(f"Error loading {csv_file}: {e}")
            sys.exit(1)
        
        # Generate comparison table
        enable_cot_backup = getattr(args, 'cot_backup', False)
        summary_table = generate_pruning_comparison_table(df, csv_file, k=20, num_simulations=10, use_cot_backup=enable_cot_backup)
        print(f"\nTable generation complete!")
        sys.exit(0)
    
    # Process the file (normal mode)
    # Use the dedicated CoT backup argument
    enable_cot_backup = getattr(args, 'cot_backup', False)
    results_df1, summary_df1, simulation_df1, results_df2, summary_df2, simulation_df2, exp_info = process_single_file(
        csv_file, args.max_paths, args.num_simulations, args.simulations, enable_cot_backup)
    
    if results_df1 is None or summary_df1 is None:
        print("Error processing the file!")
        sys.exit(1)
    
    # Add file info to results for parsed_output
    results_df1['source_file'] = os.path.basename(csv_file)
    summary_df1['source_file'] = os.path.basename(csv_file)
    summary_df1['method'] = 'parsed_output'
    
    if exp_info:
        for key, value in exp_info.items():
            results_df1[key] = value
            summary_df1[key] = value
    
    # Add file info for pruning results if available
    if results_df2 is not None and summary_df2 is not None:
        results_df2['source_file'] = os.path.basename(csv_file)
        summary_df2['source_file'] = os.path.basename(csv_file)
        summary_df2['method'] = 'existence_uniqueness_pruning'
        
        if exp_info:
            for key, value in exp_info.items():
                results_df2[key] = value
                summary_df2[key] = value
    
    # Print summary for parsed_output
    print(f"\nSummary for {os.path.basename(csv_file)} - Parsed Output:")
    print("="*60)
    if args.simulations:
        if 'std' in summary_df1.columns:
            print(f"{'k_paths':<8} {'total_samples':<15} {'correct_samples':<17} {'accuracy':<12} {'std':<12}")
            print("-"*72)
            for _, row in summary_df1.iterrows():
                print(f"{row['k_paths']:<8} {row['total_samples']:<15} {row['correct_samples']:<17} {row['accuracy']:<12.4f} {row['std']:<12.4f}")
        else:
            print(f"{'k_paths':<8} {'total_samples':<15} {'correct_samples':<17} {'accuracy':<12}")
            print("-"*60)
            for _, row in summary_df1.iterrows():
                print(f"{row['k_paths']:<8} {row['total_samples']:<15} {row['correct_samples']:<17} {row['accuracy']:<12.4f}")
    else:
        print(f"{'k_paths':<8} {'total_samples':<15} {'correct_samples':<17} {'accuracy':<12}")
        print("-"*60)
        for _, row in summary_df1.iterrows():
            print(f"{row['k_paths']:<8} {row['total_samples']:<15} {row['correct_samples']:<17} {row['accuracy']:<12.4f}")
    
    # Print summary for pruning results if available
    if summary_df2 is not None:
        print(f"\nSummary for {os.path.basename(csv_file)} - Existence & Uniqueness Pruning:")
        print("="*60)
        if args.simulations:
            if 'std' in summary_df2.columns:
                print(f"{'k_paths':<8} {'total_samples':<15} {'correct_samples':<17} {'accuracy':<12} {'std':<12}")
                print("-"*72)
                for _, row in summary_df2.iterrows():
                    print(f"{row['k_paths']:<8} {row['total_samples']:<15} {row['correct_samples']:<17} {row['accuracy']:<12.4f} {row['std']:<12.4f}")
            else:
                print(f"{'k_paths':<8} {'total_samples':<15} {'correct_samples':<17} {'accuracy':<12}")
                print("-"*60)
                for _, row in summary_df2.iterrows():
                    print(f"{row['k_paths']:<8} {row['total_samples']:<15} {row['correct_samples']:<17} {row['accuracy']:<12.4f}")
        else:
            print(f"{'k_paths':<8} {'total_samples':<15} {'correct_samples':<17} {'accuracy':<12}")
            print("-"*60)
            for _, row in summary_df2.iterrows():
                print(f"{row['k_paths']:<8} {row['total_samples']:<15} {row['correct_samples']:<17} {row['accuracy']:<12.4f}")
    
    # Save results
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    if args.output:
        output_file = args.output
        if not os.path.isabs(output_file):
            output_file = os.path.join(script_dir, output_file)
    else:
        base_name = os.path.splitext(os.path.basename(csv_file))[0]
        suffix = "_simulation" if args.simulations else "_majority_vote"
        output_file = os.path.join(script_dir, f"{base_name}{suffix}_ablation.csv")
    
    # Save detailed results for parsed_output
    results_df1.to_csv(output_file, index=False)
    print(f"\nDetailed results (parsed_output) saved to: {output_file}")
    
    # Save summary results for parsed_output
    summary_output_file = output_file.replace('.csv', '_summary.csv')
    summary_df1.to_csv(summary_output_file, index=False)
    print(f"Summary results (parsed_output) saved to: {summary_output_file}")
    
    # Save detailed results for pruning if available
    if results_df2 is not None:
        pruning_output_file = output_file.replace('.csv', '_pruning.csv')
        results_df2.to_csv(pruning_output_file, index=False)
        print(f"Detailed results (pruning) saved to: {pruning_output_file}")
        
        # Save summary results for pruning
        pruning_summary_file = output_file.replace('.csv', '_pruning_summary.csv')
        summary_df2.to_csv(pruning_summary_file, index=False)
        print(f"Summary results (pruning) saved to: {pruning_summary_file}")
    
    # Save simulation results if available
    if simulation_df1 is not None:
        simulation_output_file = output_file.replace('.csv', '_simulations.csv')
        simulation_df1.to_csv(simulation_output_file, index=False)
        print(f"Simulation results (parsed_output) saved to: {simulation_output_file}")
    
    if simulation_df2 is not None:
        simulation_pruning_file = output_file.replace('.csv', '_pruning_simulations.csv')
        simulation_df2.to_csv(simulation_pruning_file, index=False)
        print(f"Simulation results (pruning) saved to: {simulation_pruning_file}")
    
    # Generate plots if requested
    if args.plot and simulation_df1 is not None:
        # Plot 1: Single line with parsed_output only
        plot_file1 = output_file.replace('.csv', '_parsed_plot.png')
        plot_error_shade(simulation_df1, plot_file1, csv_file, " - Parsed Output")
        
        # Plot 2: Comparison plot with both lines (if pruning results available)
        if simulation_df2 is not None:
            plot_file2 = output_file.replace('.csv', '_comparison_plot.png')
            plot_comparison_error_shade(simulation_df1, simulation_df2, plot_file2, csv_file)
        else:
            print("Note: Comparison plot not generated - existence_uniqueness_pruning_result column not found")
    elif args.plot and simulation_df1 is None:
        print("Warning: --plot requires --simulations to be enabled")
    
    print(f"\nProcessing complete!")


if __name__ == "__main__":
    main()
